---
kind: pipeline
type: docker
name: default

steps:
- name: build and push
  image: plugins/docker
  settings:
    repo: registry.internal.loganmarchione.xyz/loganmarchione/docker-geoipupdate
    registry: registry.internal.loganmarchione.xyz
    dockerfile: Dockerfile
    tags:
      - latest
      - '1.0'
    when:
      branch: master

- name: test
  image: registry.internal.loganmarchione.xyz/loganmarchione/docker-geoipupdate:1.0
  commands:
    - which geoipupdate
    - geoipupdate --version
